#page title
page_title                                : SubZone                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :                                 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : gb                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             : https://apps.apple.com/app/subzone/id6446367701                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=com.subplacement                                          # Enter Google Play Store URL.
presskit_download_link                    : https://bau.me/subzone/assets/press.zip                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").
fb_app_id                                 : 782465826821178

documentation_link                        : https://bau.me/subzone-docs/

app_icon                                  : assets/subzone-logo.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : "SubZone"                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : "Subwoofer placement optimizer"                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Optimize the position of your subwoofer to maximise your listening experience
og_description                            : Optimize the position of your subwoofer to maximise your listening experience
twitter_description                       : Optimize the position of your subwoofer to maximise your listening experience
enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Sonic Baume LTD                                
your_link                                 : https://sonic.bau.me/                  
your_city                                 :                                 
email_address                             : 
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Acoustic simulation
    description                           : Simulates the effect of placing your subwoofer in each possible zone of your room
    fontawesome_icon_name                 : microchip
    
  - title                                 : Scoring
    description                           : Calculates a score out of 10 for how well each zone performs
    fontawesome_icon_name                 : list-ol

  - title                                 : Recommendations
    description                           : Recommends the optimum zone(s), marked with a star
    fontawesome_icon_name                 : star

  - title                                 : Plots
    description                           : Plots the frequency response for each zone, showing which frequencies are boosted/cut and by how much
    fontawesome_icon_name                 : chart-line

  - title                                 : Multi-position
    description                           : Supports optimization for multiple listening positions
    fontawesome_icon_name                 : user-friends
  
  # - title                                 : Materials
  #   description                           : Uses information about the construction materials of the room to improve the accuracy of the simulation
  #   fontawesome_icon_name                 : trowel-bricks

  - title                                 : Easy-to-use
    description                           : Simple interface with guided set-up tutorial
    fontawesome_icon_name                 : user-check

  - title                                 : Documentation
    description                           : Detailed documentation with a comprehensive FAQ
    fontawesome_icon_name                 : file-alt

  - title                                 : Expert support
    description                           : Real experts are on-hand to handle any questions or issues
    fontawesome_icon_name                 : user-graduate

  # - title                                 : Dark mode
  #   description                           : Dark and light color schemes
  #   fontawesome_icon_name                 : adjust

  - title                                 : Respects your privacy
    description                           : Stores data locally, complies with GDPR
    fontawesome_icon_name                 : shield-alt



# Theme Settings
topbar_color                              : "#0091ad"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/subzone-background-bw.webp                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#004C6D"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "rgb(0, 101, 144)"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "rgb(33, 50, 62)"
feature_icons_background_color            : "rgb(183, 201, 216)"
# feature_icons_foreground_color            : "rgb(0, 52, 77)"
# feature_icons_background_color            : "rgb(135, 206, 255)"
# feature_icons_foreground_color            : "rgb(52, 43, 75)"
# feature_icons_background_color            : "rgb(205, 192, 233)"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
